In [3]:
# install openslide, histomics_stream, pandas
!apt-get update
!apt-get install -y openslide-tools
!pip install cucim
!pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
!pip install openslide-python
!pip install histomics_stream 'large_image[openslide]' scikit_image --find-links https://girder.github.io/large_image_wheels
!pip install pandas
!pip install pyarrow

# install mil library with extra ray[tune]
user = 'cooperlab' #git username
token = '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' #personal access token - see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
branch = 'dev'
!python -m pip install git+https://{user}:{token}@github.com/PathologyDataScience/mil.git@{branch}#egg=mil[ray]

# imports
from cucim import CuImage
import json
from mil.io.reader import read_record, peek
import numpy as np
import os
import pandas as pd
import sys
import tensorflow as tf
from time import time

# add mil to system path for imports
sys.path.append("/tf/notebooks/histomics_stream/")

Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openslide-tools is already the newest version (3.4.1+dfsg-4).
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Looking in indexes: https://pypi.org/simple, https://developer.down

In [23]:
# parameters
path = '/data/renal_allograft/northwestern/features/EfficientNetV2S_224_112_20X/'
mapping = {'SVS_FileName': 'name', 'G': 'g', 'PTC': 'ptc',
           'V': 'v', 'TG': 'tg', 'CG': 'cg', 'MM': 'mm', 'CI': 'ci',
           'CT': 'ct', 'CV': 'cv', 'I': 'i', 'T': 't', 'AH': 'ah'}
scores = [mapping[key] for key in mapping.keys()]
files = [file for file in os.listdir(path) if os.path.splitext(file)[1] == ".tfr"]

# get lists of .tfr variables for de-serialization
serialized = list(tf.data.TFRecordDataset(path+files[0]))[0]
variables = peek(serialized)

# generate tfrecord index file for DALI
!tfrecord2idx {path+files[0]} ./{files[0]}.idx

variables

{'label_g': 'float_list',
 'number_pixel_columns_for_tile': 'int64_list',
 'label_v': 'float_list',
 'label_stain': 'bytes_list',
 'slide_index': 'int64_list',
 'histomics_version': 'bytes_list',
 'shape': 'int64_list',
 'number_tile_rows_for_slide': 'int64_list',
 'created': 'bytes_list',
 'label_t': 'float_list',
 'filename': 'bytes_list',
 'chunk_left': 'int64_list',
 'slide_group': 'bytes_list',
 'number_pixel_rows_for_slide': 'int64_list',
 'label_cg': 'float_list',
 'label_index': 'float_list',
 'scan_magnification': 'float_list',
 'label_cv': 'float_list',
 'label_mm': 'float_list',
 'number_pixel_rows_for_chunk': 'int64_list',
 'number_pixel_columns_for_slide': 'int64_list',
 'tile_top': 'int64_list',
 'level': 'int64_list',
 'read_magnification': 'float_list',
 'chunk_top': 'int64_list',
 'label_ah': 'float_list',
 'number_tile_columns_for_slide': 'int64_list',
 'label_model_name': 'bytes_list',
 'label_i': 'float_list',
 'number_pixel_rows_for_tile': 'int64_list',
 'slide_nam

In [41]:
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec

# translate features to dali "features" dictionary
mapping = {"float_list": (tfrec.float32, 0.),
           "bytes_list": (tfrec.string, ""),
           "int64_list": (tfrec.int64, -1)}
dali_features = {}
for v in variables:
    if variables[v] != "bytes_list":
        dali_features[v] = tfrec.VarLenFeature(mapping[variables[v]][0],
                                               mapping[variables[v]][1])
    
pipe = Pipeline(batch_size=1, num_threads=4, device_id=0)
with pipe:
    inputs = fn.readers.tfrecord(
        path=path+files[0],
        index_path=files[0] + ".idx",
        features=dali_features
    )
    pipe.set_outputs(*[inputs[k] for k in inputs.keys()])
    
pipe.build()
pipe.run()

(TensorListCPU(
     [[0.]],
     dtype=DALIDataType.FLOAT,
     num_samples=1,
     shape=[(1,)]),
 TensorListCPU(
     [[224]],
     dtype=DALIDataType.INT64,
     num_samples=1,
     shape=[(1,)]),
 TensorListCPU(
     [[0.]],
     dtype=DALIDataType.FLOAT,
     num_samples=1,
     shape=[(1,)]),
 TensorListCPU(
     [[0 0 ... 0 0]],
     dtype=DALIDataType.INT64,
     num_samples=1,
     shape=[(6161,)]),
 TensorListCPU(
     [[6161 1280]],
     dtype=DALIDataType.INT64,
     num_samples=1,
     shape=[(2,)]),
 TensorListCPU(
     [[235]],
     dtype=DALIDataType.INT64,
     num_samples=1,
     shape=[(1,)]),
 TensorListCPU(
     [[3.]],
     dtype=DALIDataType.FLOAT,
     num_samples=1,
     shape=[(1,)]),
 TensorListCPU(
     [[51184 51184 ... 42224 42224]],
     dtype=DALIDataType.INT64,
     num_samples=1,
     shape=[(6161,)]),
 TensorListCPU(
     [[26537]],
     dtype=DALIDataType.INT64,
     num_samples=1,
     shape=[(1,)]),
 TensorListCPU(
     [[0.]],
     dtype=DALIData